[build-system]
build-backend = "cmeel"
requires = ["cmeel-coinutils", "cmeel[build]"]

[project]
dependencies = ["cmeel-coinutils"]
description = "cmeel distribution for clp"
license = " EPL-2.0"
name = "cmeel-clp"
requires-python = ">= 3.10"
version = "1.17.11"

[project.urls]
homepage = "https://github.com/cmake-wheel/cmeel-clp"
upstream = "https://github.com/coin-or/clp"

[tool.cmeel]
build-number = 2
has-sitelib = false
run-tests = false

[tool.tomlsort]
all = true
